version: 2

models:
  - name: serving_ml_nanomag
    description: "Витрина для подготовки данных по магнитным наночастицам к машинному обучению. 
    Содержит параметры эксперимента и физико-химические характеристики наночастиц. 
    Удалены лишние столбцы и столбцы с большим количеством пропусков."