version: 2

models:
  - name: serving_analytics_column_stats_synergy
    description: "Аналитическая витрина: вычисляет базовые статистики по каждому столбцу витрины 
    serving_all_data_synergy (количество заполненных значений, уникальных значений, min/max и др.)."

  - name: serving_analytics_row_stats_synergy
    description: "Аналитическая витрина: вычисляет статистику полноты строк, 
    количество уникальных наночастиц, публикаций, бактерий, источников, 
    диапазон лет и число строк с заполненностью не менее 80%."

  - name: serving_analytics_top_categories_synergy
    description: "Аналитическая витрина: топ-10 наночастиц по числу экспериментов, среднее, 
    минимальное и максимальное значения viability_%, количество уникальных публикаций и бактерий, 
    годы первых и последних экспериментов."