version: 2

models:
  - name: serving_ml_nanozymes
    description: "Витрина для подготовки данных по каталитической активности наноэнзимов к машинному обучению. 
    Содержит параметры эксперимента и характеристики наночастиц. 
    Удалены лишние столбцы и столбцы с большим количеством пропусков."