version: 2

models:
  - name: serving_ml_seltox
    description: "Витрина для подготовки данных по селективной токсичности наночастиц к машинному обучению. 
    Содержит параметры эксперимента, характеристики наночастиц и бактерий. 
    Удалены лишние столбцы и столбцы с большим количеством пропусков."