version: 2

models:
  - name: serving_all_data_cytotox
    description: "Витрина, объединяющая все данные по экспериментам cytotox: 
    параметры эксперимента, справочники наночастиц, клеточных линий, публикаций и источников. 
    Используется для аналитики и построения дашбордов по токсичности наночастиц."

  - name: serving_all_data_nanomag
    description: "Витрина, объединяющая все данные по экспериментам nanomag: 
    параметры эксперимента, справочники наночастиц, публикаций, источников и параметров валидации. 
    Позволяет анализировать физико-химические и магнитные свойства наночастиц."

  - name: serving_all_data_nanozymes
    description: "Витрина, объединяющая все данные по экспериментам nanozymes: 
    параметры каталитических экспериментов, справочники наночастиц, публикаций и источников. 
    Используется для анализа каталитической активности наноэнзимов."

  - name: serving_all_data_seltox
    description: "Витрина, объединяющая все данные по экспериментам seltox: 
    параметры эксперимента, справочники наночастиц, бактерий, публикаций и источников. 
    Используется для анализа селективной токсичности наночастиц против бактерий."

  - name: serving_all_data_synergy
    description: "Витрина, объединяющая все данные по экспериментам synergy: 
    параметры эксперимента, справочники наночастиц, бактерий, лекарств, публикаций и источников. 
    Позволяет анализировать синергетические эффекты наночастиц и антибиотиков."