version: 2

models:
  - name: serving_ml_synergy
    description: "Витрина для подготовки данных по синергии наночастиц и антибиотиков к машинному обучению. 
    Содержит параметры эксперимента, характеристики наночастиц, бактерий и лекарств. 
    Удалены лишние столбцы и столбцы с большим количеством пропусков."