version: 2

models:
  - name: serving_analytics_column_stats_nanomag
    description: "Аналитическая витрина: вычисляет базовые статистики по каждому столбцу витрины 
    serving_all_data_nanomag (количество заполненных значений, уникальных значений, min/max и др.)."

  - name: serving_analytics_row_stats_nanomag
    description: "Аналитическая витрина: вычисляет статистику полноты строк, 
    количество уникальных наночастиц, публикаций, источников, 
    диапазон лет и число строк с заполненностью не менее 80%."

  - name: serving_analytics_top_categories_nanomag
    description: "Аналитическая витрина: топ-10 наночастиц по количеству экспериментов, 
    число уникальных публикаций, годы первых и последних экспериментов."