version: 2

models:
  - name: serving_analytics_column_stats_seltox
    description: "Аналитическая витрина: вычисляет базовые статистики по каждому столбцу витрины 
    serving_all_data_seltox (количество заполненных значений, количество уникальных значений, 
    min/max, avg и др.)."

  - name: serving_analytics_row_stats_seltox
    description: "Аналитическая витрина: вычисляет статистику полноты строк, 
    количество уникальных наночастиц, публикаций, бактерий, источников, 
    диапазон лет и число строк с заполненностью не менее 80%."

  - name: serving_analytics_top_categories_seltox
    description: "Аналитическая витрина: топ-10 наночастиц по числу экспериментов, 
    среднее, минимальное и максимальное значения mic_np_µg_ml_parsed, 
    количество уникальных публикаций и бактерий, годы первых и последних экспериментов."