version: 2

models:
  - name: serving_analytics_column_stats_cytotox
    description: "Аналитическая витрина: вычисляет базовые статистики по каждому столбцу 
    витрины serving_all_data_cytotox (количество заполненных значений, уникальных значений, min/max и др.)."

  - name: serving_analytics_row_stats_cytotox
    description: "Аналитическая витрина: вычисляет статистику полноты строк, 
    количество уникальных наночастиц, публикаций, клеточных линий, 
    диапазон лет и число строк с заполненностью не менее 80%."

  - name: serving_analytics_top_categories_cytotox
    description: "Аналитическая витрина: топ-10 наночастиц по количеству экспериментов, 
    средняя и экстремальные значения жизнеспособности, число уникальных клеточных линий и публикаций, 
    годы первых и последних экспериментов."