version: 2

models:
  - name: serving_ml_cytotox
    description: "Витрина для подготовки данных по цитотоксичности наночастиц к машинному обучению. 
    Содержит параметры эксперимента, физико-химические характеристики наночастиц и свойства клеточных линий. 
    Используется для построения ML-моделей по предсказанию токсичности. Удалены лишние столбцы и столбцы с большим кол-вом пропусков."